### ISSUE TITLE
Add 'Part of the EPS Community' graphic

### ISSUE THREAD

**Issue by LikkanChung** [CSSUoB/cssuob.github.io#110]

**Comment by JTWWilson** [comment]
Does one already exist or would you envision us making it?

**Comment by LikkanChung** [comment]
> Does one already exist or would you envision us making it?

This graphic: https://www.birmingham.ac.uk/Images/College-EPS-only/community-student/societies/societies-page-logos/eps-community-234x160.jpg

Should be included if adding sponsor logos
