### ISSUE TITLE
cssbham.com/calendar doesn't show HTML properly.

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#117]
![image](https://user-images.githubusercontent.com/9078727/120119709-229c0100-c191-11eb-96fa-5b0b0d7f4c56.png)

As can be seen in the image, the link appears to have been mangled and is no longer formatted properly when taken out of the calendar, probably as some sort of XSS defence. Not sure if it's possible to fix this but it made me slightly sad to see (as shown in picture).

**Comment by AlexJBanks** [comment]
![Screenshot_20210531-010200](https://user-images.githubusercontent.com/13523129/120124347-f346bd80-c1ab-11eb-95a8-11d35b267fe2.png)
Temporary fix: formatting removed from calendar event

**Comment by LikkanChung** [comment]
The calendar event detail processes the Google Calednar event description which is a bit outdated (https://github.com/CSSUoB/cssuob.github.io#calendar-events). 

See https://github.com/CSSUoB/cssuob.github.io/blob/e85299193bbe708c86cf9fe47c4b63edb2f29a30/js/calendar.js#L254 for how the text is parsed. 

The description text which may include raw HTML from the Google Calendar event is set with `textContent` to limit any chance of XSS when the Calendar event does not have any preformatting as per the custom defined tags outlined in the README.

**Comment by jedevc** [comment]
There's actually nothing stopping us from doing this - we *can* set the `innerHTML` property, but we should probably do some client side filtering first.

Unfortunately, for *fun* reasons, the common way of parsing html in javascript so we can actually do the filtering involves actually creating the document :smile: - which is the whole thing we want to avoid. I think we could get away with a hand-built parser or something for this, or just find some simple off the shelf tool for it.
