### ISSUE TITLE
Update /about in preperation for freshers

### ISSUE THREAD

**Issue by AlexJBanks** [CSSUoB/cssuob.github.io#138]
- [x] make discord more prominent
- [x] consistent join button lengths
- [x] remove animated emojis
- [x] more consistent emoji usage throughout
- [x] reorder/prune award section
- [ ] improve readablity and layout
- [ ] a general rewrite and tidy up

**Comment by JKHenes** [comment]
the award section formatting is inconsistent and could probably do with a re-order

**Comment by JKHenes** [comment]
very nitpicky, but the top two buttons could be aligned neater + the icons aren't centered?
![Screenshot_20210812-094639](https://user-images.githubusercontent.com/32176223/129167588-f84cc387-0c49-47da-8e83-7ee7d7b3893d.jpg)
