### ISSUE TITLE
Fix positioning of ascii text on index in mobile view

### ISSUE THREAD

**Issue by AlexJBanks** [CSSUoB/cssuob.github.io#161]
![image](https://user-images.githubusercontent.com/13523129/130320652-251fc753-750a-4ee7-8b15-0bc9804bcd9d.png)
For small screens, yellow comment text can be cut off at the bottom under copyright footer. Probably caused by the new floating banner in #146. 

Force logo and comment ascii text to align in center of page

**Comment by Rhysimus** [comment]
Can probably be fixed by letting everything float after the Fresher's banner - which looks big in mobile view actually. Will have a go at this and PR if successful

**Comment by Rhysimus** [comment]
Do we want to allow for overflow or further scaling of the text? I think the former, but lmk and I'll do a PR for it

**Comment by rainestormee** [comment]
Can’t recreate, is this still an issue @AlexJBanks ?
