### ISSUE TITLE
Committee Archive appears in the wrong order

### ISSUE THREAD

**Issue by Danyc0** [CSSUoB/cssuob.github.io#242]
From bottom to top, it goes 2020/2021, 2021/2022, then 2019/2020

**Comment by LikkanChung** [comment]
This behaves differently locally: 
![image](https://user-images.githubusercontent.com/20641536/163280208-806713a8-94a0-41f6-b04f-e09608512db9.png)

**Comment by MattyTheHacker** [comment]
Interestingly it is also in the correct order (21/22 -> 20/21 -> 19/20) when looking at the Netlify deployment as well.
