### ISSUE TITLE
Change the header bar to a clickable menu when the width is low

### ISSUE THREAD

**Issue by rwxhugo** [CSSUoB/cssuob.github.io#263]
It might just be my personal opinion but when resizing the page, I don't see the point of transitioning from all the menu items being on the same line to having two lines and then to a clickable menu.
It would make more sense if we directly transitioned from a one line menu to a clickable menu.
Here are screenshots with screen width to support my idea
Is this something worth changing ?

### width > 870
![Screenshot UoB Computer Science Society](https://user-images.githubusercontent.com/34518954/175990965-457a2c10-199e-47b4-ac76-94a6b52f4ba4.png)

### width <= 870
![Screenshot UoB Computer Science Society](https://user-images.githubusercontent.com/34518954/175991379-71c72a92-2f89-4bca-ac1a-c37a74e92bdc.png)

### width <= 600
![Screenshot UoB Computer Science Society](https://user-images.githubusercontent.com/34518954/175991533-36366bc1-fda3-453d-b04e-11b535f3e7b6.png)

**Comment by LMBishop** [comment]
This is probably just an oversight since the menu has expanded (the Ball link for certain is new and should probably be removed as well), and the value of 600px at the time was correct

**Comment by rwxhugo** [comment]
Alright so you think it should remain like that ? (should I close the issue ?) @LMBishop

**Comment by LMBishop** [comment]
Nah, it should turn into a hamburger menu when it starts to overflow. I think a value needs adjusting somewhere.
