### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by rainestormee** [CSSUoB/cssuob.github.io#274]

**Comment by Harixomxsingh** [comment]
Hey I'm working on this issue,

**Comment by rainestormee** [comment]
Hiya 😁 thanks for deciding to help with working on the CSS website! 

It might be good to go for issues that are marked with “good-first-issue” first! 

Also try to avoid issues with the “community” unless you are a member of our community as they will involve a lot of tribal knowledge!

But please feel to contribute on other issues!
Thanks! 🎉

**Comment by MattyTheHacker** [comment]
I've brought main up to date and prepped to swap default branch to main and Netlify to deploy from main. Unless there's any objections I'll action this tomorrow (hopefully)
