### ISSUE TITLE
Update /ball to reflect the fact the Ball has happened

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#278]
I think leaving ball/2022 as it is would be fine but maybe stopping /ball from redirecting you and instead make a /ball page that tells you what the Ball is. So, remove redirect; create /ball page; add a link from /ball to /ball/2022 so people can look at the past events

**Comment by rainestormee** [comment]
Might be good to add details of the lockdown ball too

**Comment by LMBishop** [comment]
Potentially related to the /events timeline thing we discussed a while back
