### ISSUE TITLE
No favicon showing on /ball/2021 and /ball/2020

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#296]
There appears to be no favicon showing on the /ball/2021 and /ball/2020 pages but there is on the /ball/2022 page. It has a different favicon from the rest of the site as it's part of the Ball colour scheme, feels like the other pages have slipped down the cracks

**Comment by TheoXIII** [comment]
Well spotted - I forgot to add the favicon to the 2021 and 2022 directories. I'll open a pull request for it now.

**Comment by JTWWilson** [comment]
I wonder if there's a way to put the favicon into the /ball folder and for the sub folders to then inherit it? Not sure if that's how it works but it seems like the nicest solution
