### ISSUE TITLE
Make sponsorship proposal easily accessible on website

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#298]
Given this is a pretty important part of the society, I think it should probably be on the navigation bar at the top? I'm wary that the bar is getting quite full though

**Comment by LMBishop** [comment]
How about another drop-down called something like "Documents" or "Other" for stuff like this

**Comment by MattyTheHacker** [comment]
I think having it on the bar on it's own could work, maybe shorten it so "Sponsor" in the interests of space.
Could then also make a whole page just dedicated to sponsorship stuff so that we're not "wasting" the space
