### ISSUE TITLE
Add instructions for how to get external membership

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/cssuob.github.io#306]
alumni have to apply for an external account with the guild. 
add instructions somewhere explaining how to do it

**Comment by LikkanChung** [comment]
User Story:

As a graduate with a guest account (which I made between my A level results, and getting a uni account)
I would like to get an external guild membership 
So that I can buy a CSS External membership

**Comment by JTWWilson** [comment]
I think @jedevc has been trying to get an external membership, he might be able to explain how that worked?
