### ISSUE TITLE
Update /agendas page

### ISSUE THREAD

**Issue by rainestormee** [CSSUoB/cssuob.github.io#308]
This will be a long one done by someone with access to the drive, will involved exporting all of the agendas as PDF and adding them to the website.

Good luck whoever goes for this.

Might also be nice to order the agendas so the newest is at the top of the page as opposed to the bottom.

**Comment by MattyTheHacker** [comment]
Worth noting some of the meetings don't actually have an agenda, just minutes. 
In these cases, an agenda will need to be created - or that meeting left off the list entirely.

**Comment by rainestormee** [comment]
I'd say an agenda would need to be created for transparency, as opposed to leaving it off.

**Comment by MattyTheHacker** [comment]
yeah I'd tend to agree
