### ISSUE TITLE
Constitution page

### ISSUE THREAD

**Issue by jedevc** [CSSUoB/cssuob.github.io#35]
As of d272415, the constitution is linked on the /about page.

We should have a separate page that includes the constitution (preferably in a number of formats, like google docs, pdf, etc) and a description of what we use it for.

However, we need to decide:

- What URL we have it at
- How we link to it

**Comment by LikkanChung** [comment]
I think it should be linked from the about page as it is now, but the link directs so either
- a PDF file, or
- a a dedicated page for the document

And there should be a short-link with cssbham.com/constitution

**Comment by jedevc** [comment]
This has been fixed for a while.
