### ISSUE TITLE
Copyright line in LICENSE file

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/cssuob.github.io#350]
Just noticed this in the license file, does this need to be fixed? 

https://github.com/CSSUoB/cssuob.github.io/blob/682a03c28c770416140d185516245c23040ab60b/LICENSE#L190

**Comment by LMBishop** [comment]
Those are the instructions on how to apply the license, it's a placeholder for when you want to add that text as a license header etc.

**Comment by MattyTheHacker** [comment]
ah yes, I can't read :) lmao ty
