### ISSUE TITLE
Description for Ballot Tex image (on page: /tex) should include EGMs in description

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/cssuob.github.io#359]
Currently the description box for the Ballot Tex image on the page https://cssbham.com/tex specifies that the stickers of this image are only given out at AGMs. This is incorrect as I received a sticker myself, today, at an EGM. I propose the description box be updated to reflect this. For example:
"TeX exercising their democratic rights as a CSS member. Stickers are handed out at our AGM and our EGMs."

**Comment by LMBishop** [comment]
Perhaps just "our elections"
