### ISSUE TITLE
Create /events and remove /clubs from the nav bar

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#374]
I think the hierarchy should be:
- /events
  - /clubs (perhaps renamed to /workshops because that's really what it is)
  - /hackathons

I think the Ball is big enough still to deserve it's own page.

The new /events page should have some examples of what our events are, what to expect from those events and when to expect them.

**Comment by LMBishop** [comment]
Probably ties in with what Sofia was going to make. Which should also be an issue on here tbh
