### ISSUE TITLE
Banner references old newsletter

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/cssuob.github.io#438]
https://cssbham.com/newsletter/looking-back-at-2022-23

The banner at the top of this page references the newsletter from 2021

**Comment by Thatsmusic99** [comment]
Caused by these lines:
https://github.com/CSSUoB/cssuob.github.io/blob/7386358f33235a6d26c84b4d7f0737948deeccab/_layouts/post.html#L19-L21

Can probably comment out for the month then re-introduce it for results day with the updated newsletter.

**Comment by AlexJBanks** [comment]
For context, this was meant to be a temporary solution to drive more traffic to the intro page that year [#146], with the intention to delete it from the source code after Freshers 2021.

That then changed into a desire to keep the banner long term (as it was successful), but refactor the code to make it easier to change the content of the banner and if it was even displayed in the first place [part of #153]. So a temporary solution was used to hide the banner and come back to it later. [#152 #180]

The banner is technically 2 separate instances, one in `/_layouts/post.html` and one in `/_layouts/page.html`. It should be revised to one piece of code that performs the same function across both pages, and can be maintained from one place
