### ISSUE TITLE
Membership page soon to be out of date

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/cssuob.github.io#448]
https://cssbham.com/membership will need to be updated at some point when we have a concrete idea of external members for the coming year. On hold until the policy has actually been written.

I'll update the below link with the most recent news we have: 
https://www.guildofstudents.com/news/article/website/Guild-Statement-Confirmation-of-the-reintroduction-of-External-Memberships/

**Comment by MattyTheHacker** [comment]
https://www.guildofstudents.com/about/memberships/externalapplication/reapply/
https://www.guildofstudents.com/about/memberships/

**Comment by CarrotManMatt** [comment]
Which one would we redirect to if we aren't going to know whether the user needs an external membership or not?

**Comment by MattyTheHacker** [comment]
Ah well you see that's the best bit - we don't because the policy hasn't been written yet

**Comment by MattyTheHacker** [comment]
As a general rule it'll just be if you're a full student, you're a standard member. If you're anything else - external

**Comment by MattyTheHacker** [comment]
then the main difference from there is that if you're on a leave of absence or a member of staff then you don't need a dbs but if you're anything else then you do

**Comment by CarrotManMatt** [comment]
Who would have guess that this issue is tagged as `on-hold` for a reason! /s
