### ISSUE TITLE
Can’t access /about page on mobile

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#474]
Trying to tap a root menu icon, in particular the /about and /ball pages on mobile doesn’t work. If you tap the about sidebar option it just shows a drop down for `-membership`

**Comment by MattyTheHacker** [comment]
not sure there's really a solution other than just adding the about page as a child of that menu as well as the main link? 
Also RE: the ball link it's not an issue because all that link does is re-direct to the most recent year page anyway

**Comment by JTWWilson** [comment]
Yeah, I agree, this seems like the best solution
