### ISSUE TITLE
Calendar clickable events

### ISSUE THREAD

**Issue by LikkanChung** [CSSUoB/cssuob.github.io#5]
When looking at the calendar, it should be possible to click on an event where it displays more information about the event, such as
- Start / End Time
- Location
- Description

Additionally, it should be possible to format the description to display different text fields, such as links to Facebook events

**Comment by LikkanChung** [comment]
Proposed solution:
https://fullcalendar.io/docs/eventClick

Use it to get info and then place in a div and reposition

**Comment by LikkanChung** [comment]
Addressed in PR #10 https://github.com/CSSUoB/cssuob.github.io/pull/10

**Comment by jedevc** [comment]
Fixed in #10.
