### ISSUE TITLE
Add number of attendees to ball 2023 page

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/cssuob.github.io#504]
The 2023 ball page currently has a link to https://cssbham.com/join, this should be replaced with the number of attendees

**Comment by sejal-bansal** [comment]
@CarrotManMatt Can I work on this issue? If yes, could you please assign it to me?

**Comment by MattyTheHacker** [comment]
> @CarrotManMatt Can I work on this issue? If yes, could you please assign it to me?

Where you gonna get the number of attendees from chief?
