### ISSUE TITLE
Add shortcut URL to Whatsapp community

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/cssuob.github.io#509]
I do not know what the link to the community is, but it would be good to get it as a shortcut at https://cssbham.com/whatsapp

**Comment by MattyTheHacker** [comment]
ideally I'd like to "legitimise" the whatsapp as little as possible - it's mainly just there to maintain some level of interaction with those that exclusively use WhatsApp as opposed to a dedicated comms platform

**Comment by CarrotManMatt** [comment]
Would this be something to **not** add to the /links page being created in #501 then?
