### ISSUE TITLE
Committee Pictures

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#98]
Around most of the pictures of the committee on https://cssbham.com/committee and https://cssbham.com/committee-archive.html there is an additional bit of white padding that looks a bit odd. 

Seems like it should be relatively simple to adjust these photos to make them the right aspect ratio.

Also, Tayyab isn't on the current committee nor is Ammaar on the committee archive.

**Comment by JTWWilson** [comment]
Seems to be fixed for me (Google Chrome, Windows) but there is some whitespace for Jacqui (Firefox, Linux)
![image](https://user-images.githubusercontent.com/9078727/112485346-bf49b900-8d72-11eb-9e6f-974f8d27fffc.png)

**Comment by jedevc** [comment]
The white bars should be fixed by #108, though it solves it by scaling them. Obviously not ideal, but it provides a nice backup in case provided descriptions are too long.
